### ISSUE TITLE
[棋譜画面]棋譜に６１手以上表示される

### ISSUE THREAD

**Issue by smd101** [smd101/panda#2]
# 問題の背景
連続してゲームを行うと、以前のゲームの棋譜が初期化されていない。

# 何が問題なのか
ゲームの純粋な棋譜が把握できない。また、以前の棋譜が閲覧できてしまう。

# 問題の解決策
【暫定対応】
棋譜画面を非表示

【恒久対応】
純粋な棋譜のみを表示できるようにする。

**Comment by akiko12** [comment]
61手以上表示されるのはCPU対戦のときに発生。
今は新しくゲームを始める際棋譜をリセットしているので
対戦画面から離れる際リセットするように変更する。

**Comment by akiko12** [comment]
画面フロー変更予定のため、恒久対応はその後行う。
https://github.com/smd101/panda/issues/15

それまでは暫定対応。

**Comment by akiko12** [comment]
https://github.com/smd101/panda/issues/2#issuecomment-415693373
と書いたが、画面フローを見直す予定なので、恒久対応はその後行う。
https://github.com/smd101/panda/issues/15

まずは暫定対応を行う。
